name: snippets

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  did_plc:
    path: ../packages/did_plc
  bluesky:
    path: ../packages/bluesky
  bluesky_text:
    path: ../packages/bluesky_text

dev_dependencies:
  lints: ^6.0.0
